return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	lazy = vim.fn.argc(-1) == 0, -- load treesitter early when opening a file from the cmdline
	cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
	keys = {
		{ "<C-space>", desc = "Increment Selection" },
		{ "<C-S-space>", desc = "Decrement Selection", mode = "x" },
	},
	opts = {
		ensure_installed = {
			"bash",
			"comment",
			"css",
			"html",
			"javascript",
			"jsdoc",
			"jsonc",
			"lua",
			"markdown",
			"regex",
			"scss",
			"toml",
			"typescript",
			"yaml",
			"golang",
			"python",
			"rust",
			"java",
			"dockerfile",
			"graphql",
		},
		auto_install = true,
		highlight = { enable = true },
		indent = { enable = true },
		incremental_selection = {
			enable = true,
			keymaps = {
				init_selection = "<C-space>",
				node_incremental = "<C-space>",
				scope_incremental = false,
				node_decremental = "<C-S-space>",
			},
		},
	},
}
